basePath: /api/v1
definitions:
  request.AssetRequest:
    properties:
      filename:
        type: string
      type:
        type: string
      url:
        type: string
    type: object
  request.CreateGameRequest:
    properties:
      assets:
        items:
          $ref: '#/definitions/request.AssetRequest'
        type: array
      description:
        type: string
      developer_id:
        type: string
      price:
        type: number
      release_date:
        type: string
      title:
        type: string
    type: object
  response.AssetResponse:
    properties:
      filename:
        type: string
      id:
        type: string
      type:
        type: string
      url:
        type: string
    type: object
  response.CreateGameResponse:
    properties:
      id:
        type: string
    type: object
  response.GetGameResponse:
    properties:
      assets:
        items:
          $ref: '#/definitions/response.AssetResponse'
        type: array
      description:
        type: string
      developer_id:
        type: string
      id:
        type: string
      price:
        type: number
      release_date:
        type: string
      title:
        type: string
    type: object
  resterror.ErrGameNotFoundResponse:
    properties:
      error:
        example: game not found
        type: string
    type: object
  resterror.ErrGetGameBadRequest:
    properties:
      error:
        example: invalid game ID format
        type: string
    type: object
  resterror.ErrInternal:
    properties:
      error:
        example: Internal Server Error
        type: string
    type: object
host: localhost:8080
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: Bitnix REST API documentation
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Bitnix REST API
  version: "1.0"
paths:
  /game:
    post:
      consumes:
      - application/json
      description: Create a new game with the given details
      parameters:
      - description: Game creation request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/request.CreateGameRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/response.CreateGameResponse'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/resterror.ErrInternal'
      summary: Create a new game
      tags:
      - Game Service
  /game/{id}:
    get:
      consumes:
      - application/json
      description: Get a game using its identifier
      parameters:
      - description: Game ID (UUID)
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.GetGameResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/resterror.ErrGetGameBadRequest'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/resterror.ErrGameNotFoundResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/resterror.ErrInternal'
      summary: get a game
      tags:
      - Game Service
schemes:
- http
swagger: "2.0"
